/**
 * Copyright © 2009-2012 Nick Bargnesi <nick@den-4.com>. All rights reserved.
 *
 * inotify-java is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * inotify-java is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with inotify-java. If not, see <http://www.gnu.org/licenses/>.
 *
 * File: Event.java
 * Project: inotify-java
 * Package: com.den_4.inotify_java
 * Author: Nick Bargnesi
 */
package com.den_4.inotify_java;

import java.util.EventObject;

/**
 * Represents all events generated by inotify-java.
 * 
 * @since 2.1 Added this base class common to {@link InotifyEvent} and
 * {@link EventQueueFull}
 */
abstract class BaseEvent extends EventObject {
    private static final long serialVersionUID = 3665027631470495686L;

    /**
     * Creates a base event associated with a descriptor.
     * 
     * @param descriptor Watch or file descriptor
     * @see NativeInotify#addWatch(String, int)
     * @see NativeInotify#getFileDescriptor()
     */
    public BaseEvent(Integer descriptor) {
        super(descriptor);
    }

    /**
     * Returns the descriptor associated with this event. This descriptor can be
     * either a watch descriptor or a file descriptor. It is left to subclasses
     * to indicate which is used. {@inheritDoc}
     * 
     * @return Integer descriptor
     * @see NativeInotify#addWatch(String, int)
     * @see NativeInotify#getFileDescriptor()
     */
    @Override
    public Integer getSource() {
        return (Integer) super.getSource();
    }

}
